---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Install pre-requisites using apt
      apt:
        name:
          - python3-openshift  # OpenShift client and libraries
          - python3-yaml       # For working with YAML
          - python3-kubernetes # Kubernetes client libraries
        state: present

    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: mern-app

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/mern-backend-secret.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/frontend-deployment.yaml') | from_yaml }}" 

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/frontend-service.yaml') | from_yaml }}" 


    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/backend-deployment.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/backend-service.yaml') | from_yaml }}"
    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/mern-ingress.yaml') | from_yaml }}" 

    - name: Create Backend HPA
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/backend-hpa.yaml') | from_yaml }}"

    - name: Create Frontend HPA
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8/frontend-hpa.yaml') | from_yaml }}"