apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kushaldasari/backend-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5000
        env: 
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: DB_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: JWT_SECRET_KEY
